config/routes.rb
Rails.application.routes.draw do
  resources :people, except: [:show]

  root to: "people#index"
end

app/models/diagnosis.rb
class Diagnosis
  include Mongoid::Document

  belongs_to :person  
  field :person_id, type: String
  field :name, type: String
end

app/models/person.rb
class Person
  include Mongoid::Document
  has_many :diagnoses, autosave: true
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :notes, type: String
  field :notes2, type: String

  validates :first_name, :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.paginate(:page => params[:page], :per_page => 2)
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to root_path, notice: "The person has been created!" and return
    end
    render 'new'
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update_attributes(person_params)
      redirect_to root_path, notice: "#{@person.first_name} #{@person.last_name} has been updated!" and return
    end

    render 'edit'
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    redirect_to root_path, notice: "#{@person.first_name} #{@person.last_name} has been deleted!" and return
  end
private
  def person_params
    params.require(:person).permit(:first_name, :last_name, :email, :notes, :notes2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MongoDBExampleApp
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %p= flash[:error]
      %p= flash[:notice]
      = yield

app/views/people/_form.html.haml
.well
  = simple_form_for @person do |f|
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :notes
    = f.input :notes2
    .text-center
      = f.button :submit, class: "btn btn-primary"

app/views/people/create.html.haml
%h1 People#create
%p Find me in app/views/people/create.html.erb

app/views/people/destroy.html.haml
%h1 People#destroy
%p Find me in app/views/people/destroy.html.erb

app/views/people/edit.html.haml
%h1= "Editing #{@person.first_name} #{@person.last_name}"
= render "form"

app/views/people/index.html.haml
%h1 People
.well
  = link_to "New Person", new_person_path, class: "btn btn-primary"
- if flash[:notice]
  .alert.alert-success= flash[:notice]
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th First Name
      %th Last Name
      %th Email
      %th Notes
      %th Notes2
      %th  
      %th  
  %tbody
    - if @people.size == 0
      %tr
        %td{:colspan => "6"} No people found.
    - else
      - @people.each do |person|
        %tr
          %td= person.first_name
          %td= person.last_name
          %td= person.email
          %td= person.notes
          %td= person.notes2
          %td
            = link_to "Edit", edit_person_path(person), class: "btn btn-default"
          %td
            = button_to "Delete", person, method: :delete, data: { confirm: "Are you sure you wish to delete #{person.first_name} #{person.last_name}?" }, class: "btn btn-danger"
= will_paginate @people, renderer: BootstrapPagination::Rails

app/views/people/new.html.haml
%h1 New Person
.well
  = render "form"

app/views/people/update.html.haml
%h1 People#update
%p Find me in app/views/people/update.html.erb